save_backup_to_robonomics:
  name: Save Backup to Robonomics
  description: Create new backup, save it to IPFS and send a transaction to Robonomics blockchain with IPFS hash
  fields:
    full:
      name: Full Backup
      description: If checked, database will be added to the backup
      required: true
      selector:
        boolean:
    mosquitto_path:
      name: Path to mosquitto password file (Optional)
      description: Defines the path to mosquitto 'passwd' file will be backed up, with a default value of '/etc/mosquitto' if not specified.
      required: false
      advanced: true
      example: /etc/mosquitto
      selector:
        text:

restore_from_robonomics_backup:
  name: Restore from the Backup in Robonomics
  description: Get the latest backup from Robonomics Network and restore from it
  fields:
    mosquitto_path:
      name: Path to mosquitto password file (Optional)
      description: Defines the path to mosquitto configuration where 'passwd' file will be restored, with a default value of '/etc/mosquitto' if not specified.
      required: false
      advanced: true
      example: /etc/mosquitto
      selector:
        text:
    zigbee2mqtt_path:
      name: Path to zigbee2mqtt config (Optional)
      description: Defines the path to the zigbee2mqtt configuration where 'data' directory will be restored, with a default value of '/opt/zigbee2mqtt' if not specified.
      required: false
      advanced: true
      example: /opt/zigbee2mqtt
      selector:
        text:

save_video_to_robonomics:
  name: Save recording to robonomics
  description: Record a video, save it to IPFS and Digital Twin
  target:
      entity:
        domain: camera
  fields:
    path:
      description: This path must be set in configuration.yaml
      name: Path to save the recording
      required: true
      example: "/tmp"
      selector:
        text:
    duration:
      description: Duration of the recording in seconds (default 10s)
      name: Duration
      required: false
      selector:
        number:
          min: 1
          max: 90